version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: employeedb
      MYSQL_USER: root
      MYSQL_PASSWORD: Waybig@123
      MYSQL_ROOT_PASSWORD: Waybig@123
    ports:
      - "3307:3306"
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend-network

  app:
    image: your_app_image
    depends_on:
      - db
    ports:
      - "8082:8082"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge